import Head from "next/head";
import React from "react";
import { Inter } from "next/font/google";
import Header from "./Header";
import Footer from "./Footer";
import MainContent from "./MainContent";

interface LayoutProps {
  children: React.ReactElement;
}

const inter = Inter({ subsets: ["latin"] });

const Layout = ({ children }: LayoutProps) => {
  return (
    <>
      <Head>
        <title>Rayzor8 dev</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <MainContent>{children}</MainContent>
      <Footer />
    </>
  );
};

export default Layout;
